driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
  network:
    # Allow access to the Jenkins webui which is useful when troubleshooting
    - - forwarded_port
      - guest: 8080
        host: 9090
        auto_correct: true

provisioner:
  name: chef_zero
  data_path: test/fixtures/keys
  data_bags_path: test/fixtures/data_bags
  attributes:
    jenkins:
      master:
        host: localhost
        install_method: war
        mirror: https://updates.jenkins.io

platforms:
  - name: debian-7.11
  - name: debian-8.7
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.8
  - name: centos-7.3

suites:
  #
  # Smoke suite
  #
  - name: smoke_package_stable
    run_list: jenkins_server_wrapper::default
    attributes:
      jenkins:
        master:
          install_method: package
  - name: smoke_package_current
    run_list: jenkins_server_wrapper::default
    attributes:
      jenkins:
        master:
          channel: current
          install_method: package
  - name: smoke_war_stable
    run_list: jenkins_server_wrapper::default
    attributes:
      jenkins:
        master:
          install_method: war
          source: https://updates.jenkins.io/stable/latest/jenkins.war
  - name: smoke_war_latest
    run_list: jenkins_server_wrapper::default
    attributes:
      jenkins:
        master:
          install_method: war
          source: https://updates.jenkins.io/latest/jenkins.war

  #
  # Authentication suites
  #
  - name: authentication_private_key
    run_list: jenkins_authentication::private_key
  - name: authentication_username_password
    run_list: jenkins_authentication::username_password

  #
  # Command suites
  #
  - name: jenkins_command_execute
    run_list: jenkins_command::execute

  #
  # Credentials suites
  #
  - name: jenkins_credentials_create
    run_list: jenkins_credentials::create
  - name: jenkins_credentials_delete
    run_list: jenkins_credentials::delete

  #
  # Job suites
  #
  - name: jenkins_job_create
    run_list:
      - jenkins_job::create
      - jenkins_job::create_folder
  - name: jenkins_job_delete
    run_list: jenkins_job::delete
  - name: jenkins_job_disable
    run_list: jenkins_job::disable
  - name: jenkins_job_enable
    run_list: jenkins_job::enable
  - name: jenkins_job_build
    run_list: jenkins_job::build

  #
  # Script suites
  #
  - name: jenkins_script
    run_list: jenkins_script::execute

  #
  # Plugin suites
  #
  - name: jenkins_plugin_disable
    run_list: jenkins_plugin::disable
  - name: jenkins_plugin_enable
    run_list: jenkins_plugin::enable
  - name: jenkins_plugin_install
    run_list: jenkins_plugin::install
  - name: jenkins_plugin_uninstall
    run_list: jenkins_plugin::uninstall

  #
  # Slave suites
  #
  - name: jenkins_slave_create
    run_list:
      - jenkins_slave::create_jnlp
      - jenkins_slave::create_ssh
  - name: jenkins_slave_delete
    run_list:
      - jenkins_slave::delete_jnlp
      - jenkins_slave::delete_ssh
  - name: jenkins_slave_connect
    run_list: jenkins_slave::connect
  - name: jenkins_slave_disconnect
    run_list: jenkins_slave::disconnect
  - name: jenkins_slave_online
    run_list: jenkins_slave::online
  - name: jenkins_slave_offline
    run_list: jenkins_slave::offline

  #
  # User suites
  #
  - name: jenkins_user_create
    run_list: jenkins_user::create
  - name: jenkins_user_delete
    run_list: jenkins_user::delete
