driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
  network:
    # Allow access to the Jenkins webui which is useful when troubleshooting
    - - forwarded_port
      - guest: 8080
        host: 9090
        auto_correct: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.0.0.rc.1
  data_path: test/shared
  data_bags_path: test/fixtures/data_bags
  attributes:
    jenkins:
      master:
        host: localhost
        install_method: war
        version: '1.590'
        mirror: http://mirrors.jenkins-ci.org

platforms:
  - name: ubuntu-12.04
    run_list:
      - apt::default
      - jenkins::java
  - name: centos-6.4
    run_list:
      - yum::default
      - jenkins::java

suites:
  #
  # Smoke suite
  #
  - name: smoke_package
    includes:
      - centos-6.4 # [JENKINS-12295] APT repo does not allow version specification
    run_list: smoke::default
    attributes:
      jenkins:
        master:
          install_method: package
          version: '1.580-1.1'
  - name: smoke_package_latest
    run_list: smoke::default
    attributes:
      jenkins:
        master:
          install_method: package
          version:
  - name: smoke_war
    run_list: smoke::default
    attributes:
      jenkins:
        master:
          install_method: war
          version: '1.580.1'
          source: http://mirrors.jenkins-ci.org/war-stable/1.580.1/jenkins.war

  #
  # Authentication suites
  #
  - name: authentication
    run_list: authentication::default

  #
  # Command suites
  #
  - name: jenkins_command_execute
    run_list: jenkins_command::execute

  #
  # Credentials suites
  #
  - name: jenkins_credentials_create
    run_list: jenkins_credentials::create
  - name: jenkins_credentials_delete
    run_list: jenkins_credentials::delete

  #
  # Job suites
  #
  - name: jenkins_job_create
    run_list:
      - jenkins_job::create
      - jenkins_job::create_folder
  - name: jenkins_job_delete
    run_list: jenkins_job::delete
  - name: jenkins_job_disable
    run_list: jenkins_job::disable
  - name: jenkins_job_enable
    run_list: jenkins_job::enable

  #
  # Script suites
  #
  - name: jenkins_script
    run_list: jenkins_script::execute

  #
  # Plugin suites
  #
  - name: jenkins_plugin_disable
    run_list: jenkins_plugin::disable
  - name: jenkins_plugin_enable
    run_list: jenkins_plugin::enable
  - name: jenkins_plugin_install
    run_list: jenkins_plugin::install
  - name: jenkins_plugin_uninstall
    run_list: jenkins_plugin::uninstall

  #
  # Slave suites
  #
  - name: jenkins_slave_create
    run_list:
      - jenkins_slave::create_jnlp
      - jenkins_slave::create_ssh
  - name: jenkins_slave_delete
    run_list:
      - jenkins_slave::delete_jnlp
      - jenkins_slave::delete_ssh
  - name: jenkins_slave_connect
    run_list: jenkins_slave::connect
  - name: jenkins_slave_disconnect
    run_list: jenkins_slave::disconnect
  - name: jenkins_slave_online
    run_list: jenkins_slave::online
  - name: jenkins_slave_offline
    run_list: jenkins_slave::offline

  #
  # User suites
  #
  - name: jenkins_user_create
    run_list: jenkins_user::create
  - name: jenkins_user_delete
    run_list: jenkins_user::delete
