AllCops:
  Excludes:
    - vendor/**

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
TrailingComma:
  EnforcedStyleForMultiline: comma
