AllCops:
  Exclude:
    - 'files/**/*'
    - 'vendor/**/*'
    - 'test/shared/support/**/*'

AbcSize:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ModuleLength:
  Enabled: false
PerceivedComplexity:
  Enabled: false
RaiseArgs:
  Enabled: false
SignalException:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
TrailingComma:
  EnforcedStyleForMultiline: comma
