name              'jenkins'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures Jenkins CI Controller & Agent'
version           '11.0.1'
source_url        'https://github.com/sous-chefs/jenkins'
issues_url        'https://github.com/sous-chefs/jenkins/issues'
chef_version      '>= 16'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'oracle', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'

depends 'dpkg_autostart'
depends 'yum-epel'
